### ISSUE TITLE
二维码是怎么实现（

### ISSUE THREAD

**Issue by SteveZMTstudios** [niemingzhao/niemingzhao.github.io#24]
非常喜欢您的博客主题。我计划将其theme分支作为我的博客主题以供使用。

目前长这样：[blog.stevezmt.top](https://blog.stevezmt.top)
仓库位于[stevezmtstudios/articles](https://github.com/stevezmtstudios/articles)

但是我遇到了一个麻烦：

当我想变更"发送到手机"的实现方式从其他平台生成变更为浏览器自己生成，也就是修改`_config.yml`文件中qrcode.use的值为plugin时，我发现对应的`layout/_partial/article.ejs`会出现"qrcode 未定义"函数错误。

```
$ hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 183 ms
ERROR 
ReferenceError: /home/steve/Project/articles/themes/default/layout/page.ejs:1
 >> 1| <%- partial('_partial/article') %>
    2| 

/home/steve/Project/articles/themes/default/layout/_partial/article.ejs:76
    74|             <li class="mdui-menu-item" disabled>
    75|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 76|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    77|               <% } else { %>
    78|                 <img src="<% if (page.lang === 'zh-CN') { %>//qr.liantu.com/api.php?text=<%- page.permalink %><% } else { %>//chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    79|               <% } %>

qrcode is not defined
    at eval ("/home/steve/Project/articles/themes/default/layout/_partial/article.ejs":121:7)
    at article (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:117:32)
    at _View.renderSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:55:29)
    at Object.partial (/home/steve/Project/articles/node_modules/hexo/dist/plugins/helper/partial.js:27:17)
    at eval ("/home/steve/Project/articles/themes/default/layout/page.ejs":10:17)
    at page (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:120:67)
    at _View.render (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:37:21)
    at /home/steve/Project/articles/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/home/steve/Project/articles/node_modules/bluebird/js/release/util.js:16:23)
    at /home/steve/Project/articles/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/steve/Project/articles/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 183 ms
ERROR 
ReferenceError: /home/steve/Project/articles/themes/default/layout/page.ejs:1
 >> 1| <%- partial('_partial/article') %>
    2| 

/home/steve/Project/articles/themes/default/layout/_partial/article.ejs:76
    74|             <li class="mdui-menu-item" disabled>
    75|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 76|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    77|               <% } else { %>
    78|                 <img src="<% if (page.lang === 'zh-CN') { %>//qr.liantu.com/api.php?text=<%- page.permalink %><% } else { %>//chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    79|               <% } %>

qrcode is not defined
    at eval ("/home/steve/Project/articles/themes/default/layout/_partial/article.ejs":121:7)
    at article (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:117:32)
    at _View.renderSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:55:29)
    at Object.partial (/home/steve/Project/articles/node_modules/hexo/dist/plugins/helper/partial.js:27:17)
    at eval ("/home/steve/Project/articles/themes/default/layout/page.ejs":10:17)
    at page (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:120:67)
    at _View.render (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:37:21)
    at /home/steve/Project/articles/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/home/steve/Project/articles/node_modules/bluebird/js/release/util.js:16:23)
    at /home/steve/Project/articles/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/steve/Project/articles/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
ERROR 
ReferenceError: /home/steve/Project/articles/themes/default/layout/page.ejs:1
 >> 1| <%- partial('_partial/article') %>
    2| 

/home/steve/Project/articles/themes/default/layout/_partial/article.ejs:76
    74|             <li class="mdui-menu-item" disabled>
    75|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 76|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    77|               <% } else { %>
    78|                 <img src="<% if (page.lang === 'zh-CN') { %>//qr.liantu.com/api.php?text=<%- page.permalink %><% } else { %>//chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    79|               <% } %>

qrcode is not defined
    at eval ("/home/steve/Project/articles/themes/default/layout/_partial/article.ejs":121:7)
    at article (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:117:32)
    at _View.renderSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:55:29)
    at Object.partial (/home/steve/Project/articles/node_modules/hexo/dist/plugins/helper/partial.js:27:17)
    at eval ("/home/steve/Project/articles/themes/default/layout/page.ejs":10:17)
    at page (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:120:67)
    at _View.render (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:37:21)
    at /home/steve/Project/articles/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/home/steve/Project/articles/node_modules/bluebird/js/release/util.js:16:23)
    at /home/steve/Project/articles/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/steve/Project/articles/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
ERROR 
ReferenceError: /home/steve/Project/articles/themes/default/layout/post.ejs:1
 >> 1| <%- partial('_partial/article') %>
    2| 

/home/steve/Project/articles/themes/default/layout/_partial/article.ejs:76
    74|             <li class="mdui-menu-item" disabled>
    75|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 76|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    77|               <% } else { %>
    78|                 <img src="<% if (page.lang === 'zh-CN') { %>//qr.liantu.com/api.php?text=<%- page.permalink %><% } else { %>//chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    79|               <% } %>

qrcode is not defined
    at eval ("/home/steve/Project/articles/themes/default/layout/_partial/article.ejs":121:7)
    at article (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:117:32)
    at _View.renderSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:55:29)
    at Object.partial (/home/steve/Project/articles/node_modules/hexo/dist/plugins/helper/partial.js:27:17)
    at eval ("/home/steve/Project/articles/themes/default/layout/post.ejs":10:17)
    at post (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:120:67)
    at _View.render (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:37:21)
    at /home/steve/Project/articles/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/home/steve/Project/articles/node_modules/bluebird/js/release/util.js:16:23)
    at /home/steve/Project/articles/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/steve/Project/articles/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
INFO  Generated: archives/index.html
INFO  Generated: archives/2024/11/index.html
INFO  Generated: archives/2024/index.html
INFO  Generated: index.html
INFO  4 files generated in 58 ms
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
ERROR 
ReferenceError: /home/steve/Project/articles/themes/default/layout/page.ejs:1
 >> 1| <%- partial('_partial/article') %>
    2| 

/home/steve/Project/articles/themes/default/layout/_partial/article.ejs:76
    74|             <li class="mdui-menu-item" disabled>
    75|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 76|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    77|               <% } else { %>
    78|                 <img src="<% if (page.lang === 'zh-CN') { %>//qr.liantu.com/api.php?text=<%- page.permalink %><% } else { %>//chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    79|               <% } %>

qrcode is not definedhexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 183 ms
ERROR 
ReferenceError: /home/steve/Project/articles/themes/default/layout/page.ejs:1
 >> 1| <%- partial('_partial/article') %>
    2| 

/home/steve/Project/articles/themes/default/layout/_partial/article.ejs:76
    74|             <li class="mdui-menu-item" disabled>
    75|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 76|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    77|               <% } else { %>
    78|                 <img src="<% if (page.lang === 'zh-CN') { %>//qr.liantu.com/api.php?text=<%- page.permalink %><% } else { %>//chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    79|               <% } %>

qrcode is not defined
    at eval ("/home/steve/Project/articles/themes/default/layout/_partial/article.ejs":121:7)
    at article (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:117:32)
    at _View.renderSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:55:29)
    at Object.partial (/home/steve/Project/articles/node_modules/hexo/dist/plugins/helper/partial.js:27:17)
    at eval ("/home/steve/Project/articles/themes/default/layout/page.ejs":10:17)
    at page (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:120:67)
    at _View.render (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:37:21)
    at /home/steve/Project/articles/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/home/steve/Project/articles/node_modules/bluebird/js/release/util.js:16:23)
    at /home/steve/Project/articles/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/steve/Project/articles/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
ERROR 
ReferenceError: /home/steve/Project/articles/themes/default/layout/page.ejs:1
 >> 1| <%- partial('_partial/article') %>
    2| 

/home/steve/Project/articles/themes/default/layout/_partial/article.ejs:76
    74|             <li class="mdui-menu-item" disabled>
    75|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 76|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    77|               <% } else { %>
    78|                 <img src="<% if (page.lang === 'zh-CN') { %>//qr.liantu.com/api.php?text=<%- page.permalink %><% } else { %>//chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    79|               <% } %>

qrcode is not defined
    at eval ("/home/steve/Project/articles/themes/default/layout/_partial/article.ejs":121:7)
    at article (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:117:32)
    at _View.renderSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:55:29)
    at Object.partial (/home/steve/Project/articles/node_modules/hexo/dist/plugins/helper/partial.js:27:17)
    at eval ("/home/steve/Project/articles/themes/default/layout/page.ejs":10:17)
    at page (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:120:67)
    at _View.render (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:37:21)
    at /home/steve/Project/articles/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/home/steve/Project/articles/node_modules/bluebird/js/release/util.js:16:23)
    at /home/steve/Project/articles/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/steve/Project/articles/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
ERROR 
ReferenceError: /home/steve/Project/articles/themes/default/layout/post.ejs:1
 >> 1| <%- partial('_partial/article') %>
    2| 

/home/steve/Project/articles/themes/default/layout/_partial/article.ejs:76
    74|             <li class="mdui-menu-item" disabled>
    75|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 76|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    77|               <% } else { %>
    78|                 <img src="<% if (page.lang === 'zh-CN') { %>//qr.liantu.com/api.php?text=<%- page.permalink %><% } else { %>//chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    79|               <% } %>

qrcode is not defined
    at eval ("/home/steve/Project/articles/themes/default/layout/_partial/article.ejs":121:7)
    at article (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:117:32)
    at _View.renderSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:55:29)
    at Object.partial (/home/steve/Project/articles/node_modules/hexo/dist/plugins/helper/partial.js:27:17)
    at eval ("/home/steve/Project/articles/themes/default/layout/post.ejs":10:17)
    at post (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:120:67)
    at _View.render (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:37:21)
    at /home/steve/Project/articles/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/home/steve/Project/articles/node_modules/bluebird/js/release/util.js:16:23)
    at /home/steve/Project/articles/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/steve/Project/articles/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
INFO  Generated: archives/index.html
INFO  Generated: archives/2024/11/index.html
INFO  Generated: archives/2024/index.html
INFO  Generated: index.html
INFO  4 files generated in 58 ms
    at eval ("/home/steve/Project/articles/themes/default/layout/_partial/article.ejs":121:7)
    at article (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:117:32)
    at _View.renderSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:55:29)
    at Object.partial (/home/steve/Project/articles/node_modules/hexo/dist/plugins/helper/partial.js:27:17)
    at eval ("/home/steve/Project/articles/themes/default/layout/page.ejs":10:17)
    at page (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:120:67)
    at _View.render (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:37:21)
    at /home/steve/Project/articles/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/home/steve/Project/articles/node_modules/bluebird/jhexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 183 ms
ERROR 
ReferenceError: /home/steve/Project/articles/themes/default/layout/page.ejs:1
 >> 1| <%- partial('_partial/article') %>
    2| 

/home/steve/Project/articles/themes/default/layout/_partial/article.ejs:76
    74|             <li class="mdui-menu-item" disabled>
    75|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 76|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    77|               <% } else { %>
    78|                 <img src="<% if (page.lang === 'zh-CN') { %>//qr.liantu.com/api.php?text=<%- page.permalink %><% } else { %>//chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    79|               <% } %>

qrcode is not defined
    at eval ("/home/steve/Project/articles/themes/default/layout/_partial/article.ejs":121:7)
    at article (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:117:32)
    at _View.renderSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:55:29)
    at Object.partial (/home/steve/Project/articles/node_modules/hexo/dist/plugins/helper/partial.js:27:17)
    at eval ("/home/steve/Project/articles/themes/default/layout/page.ejs":10:17)
    at page (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:120:67)
    at _View.render (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:37:21)
    at /home/steve/Project/articles/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/home/steve/Project/articles/node_modules/bluebird/js/release/util.js:16:23)
    at /home/steve/Project/articles/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/steve/Project/articles/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
ERROR 
ReferenceError: /home/steve/Project/articles/themes/default/layout/page.ejs:1
 >> 1| <%- partial('_partial/article') %>
    2| 

/home/steve/Project/articles/themes/default/layout/_partial/article.ejs:76
    74|             <li class="mdui-menu-item" disabled>
    75|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 76|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    77|               <% } else { %>
    78|                 <img src="<% if (page.lang === 'zh-CN') { %>//qr.liantu.com/api.php?text=<%- page.permalink %><% } else { %>//chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    79|               <% } %>

qrcode is not defined
    at eval ("/home/steve/Project/articles/themes/default/layout/_partial/article.ejs":121:7)
    at article (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:117:32)
    at _View.renderSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:55:29)
    at Object.partial (/home/steve/Project/articles/node_modules/hexo/dist/plugins/helper/partial.js:27:17)
    at eval ("/home/steve/Project/articles/themes/default/layout/page.ejs":10:17)
    at page (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:120:67)
    at _View.render (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:37:21)
    at /home/steve/Project/articles/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/home/steve/Project/articles/node_modules/bluebird/js/release/util.js:16:23)
    at /home/steve/Project/articles/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/steve/Project/articles/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
ERROR 
ReferenceError: /home/steve/Project/articles/themes/default/layout/post.ejs:1
 >> 1| <%- partial('_partial/article') %>
    2| 

/home/steve/Project/articles/themes/default/layout/_partial/article.ejs:76
    74|             <li class="mdui-menu-item" disabled>
    75|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 76|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    77|               <% } else { %>
    78|                 <img src="<% if (page.lang === 'zh-CN') { %>//qr.liantu.com/api.php?text=<%- page.permalink %><% } else { %>//chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    79|               <% } %>

qrcode is not defined
    at eval ("/home/steve/Project/articles/themes/default/layout/_partial/article.ejs":121:7)
    at article (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:117:32)
    at _View.renderSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:55:29)
    at Object.partial (/home/steve/Project/articles/node_modules/hexo/dist/plugins/helper/partial.js:27:17)
    at eval ("/home/steve/Project/articles/themes/default/layout/post.ejs":10:17)
    at post (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:120:67)
    at _View.render (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:37:21)
    at /home/steve/Project/articles/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/home/steve/Project/articles/node_modules/bluebird/js/release/util.js:16:23)
    at /home/steve/Project/articles/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/steve/Project/articles/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
INFO  Generated: archives/index.html
INFO  Generated: archives/2024/11/index.html
INFO  Generated: archives/2024/index.html
INFO  Generated: index.html
INFO  4 files generated in 58 mss/release/util.js:16:23)
    at /home/steve/Project/articles/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/steve/Project/articles/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
ERROR 
ReferenceError: /home/steve/Project/articles/themes/default/layout/post.ejs:1
 >> 1| <%- partial('_partial/article') %>
    2| 

/home/steve/Project/articles/themes/default/layout/_partial/article.ejs:76
    74|             <li class="mdui-menu-item" disabled>
    75|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 76|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    77|               <% } else { %>
    78|                 <img src="<% if (page.lang === 'zh-CN') { %>//qr.liantu.com/api.php?text=<%- page.permalink %><% } else { %>//chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    79|               <% } %>

qrcode is not defined
    at eval ("/home/steve/Project/articles/themes/default/layout/_partial/article.ejs":121:7)
    at article (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiledSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:117:32)
    at _View.renderSync (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:55:29)
    at Object.partial (/home/steve/Project/articles/node_modules/hexo/dist/plugins/helper/partial.js:27:17)
    at eval ("/home/steve/Project/articles/themes/default/layout/post.ejs":10:17)
    at post (/home/steve/Project/articles/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:120:67)
    at _View.render (/home/steve/Project/articles/node_modules/hexo/dist/theme/view.js:37:21)
    at /home/steve/Project/articles/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/home/steve/Project/articles/node_modules/bluebird/js/release/util.js:16:23)
    at /home/steve/Project/articles/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/steve/Project/articles/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
INFO  Generated: archives/index.html
INFO  Generated: archives/2024/11/index.html
INFO  Generated: archives/2024/index.html
INFO  Generated: index.html
INFO  4 files generated in 58 ms
```
我查阅了一些文档，猜测是需要导入jQuery.qrcode.js

但是我必须说我在前端几乎完全没有经验。我也没能在您的项目仓库中找到相关的js以参考其使用方法。

所以我想来咨询一下如何应用这一部分。

抱歉占用您的宝贵时间。若能回复不胜感激！

**Comment by SteveZMTstudios** [comment]
搞清楚了，安装`npm i -S hexo-helper-qrcode`

**Comment by niemingzhao** [comment]
> 搞清楚了，安装`npm i -S hexo-helper-qrcode`

是的，OK。
